//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8SB1_Register_Enums.h>

//=============================================================================
// Automatically generated interrupt routines must be commented out here
// every time the Simplicity Studio configuration tool is run because they
// are defined in their respective modules.
//=============================================================================

/*
 //-----------------------------------------------------------------------------
 // TIMER0_ISR
 //-----------------------------------------------------------------------------
 //
 // TIMER0 ISR Content goes here. Remember to clear flag bits:
 // TCON::TF0 (Timer 0 Overflow Flag)
 //
 //-----------------------------------------------------------------------------
 SI_INTERRUPT (TIMER0_ISR, TIMER0_IRQn)
 {

 }

 //-----------------------------------------------------------------------------
 // TIMER2_ISR
 //-----------------------------------------------------------------------------
 //
 // TIMER2 ISR Content goes here. Remember to clear flag bits:
 // TMR2CN0::TF2H (Timer # High Byte Overflow Flag)
 // TMR2CN0::TF2L (Timer # Low Byte Overflow Flag)
 //
 //-----------------------------------------------------------------------------
 SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn)
 {

 }

 //-----------------------------------------------------------------------------
 // SMBUS0_ISR
 //-----------------------------------------------------------------------------
 //
 // SMBUS0 ISR Content goes here. Remember to clear flag bits:
 // SMB0CN0::SI (SMBus Interrupt Flag)
 //
 //-----------------------------------------------------------------------------
 SI_INTERRUPT (SMBUS0_ISR, SMBUS0_IRQn)
 {

 }
 */

